### ISSUE TITLE
module naming not PEP8 compliant

### ISSUE THREAD

**Issue by orbeckst** [dotsdl/MDSynthesis#11]
Having all modules start with uppercase looks a bit weird and is not the recommendation of [PEP8](https://www.python.org/dev/peps/pep-0008/#naming-conventions):

* "**Modules** should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged."
* "**Class names** should normally use the CapWords convention. "
* "**Function names** should be lowercase, with words separated by underscores as necessary to improve readability."

(I know that e.g. MDAnalysis is also not fully compliant but this is a new project and you still have a chance to do it right without p***ing off too many users...)

**Comment by dotsdl** [comment]
We do still have the flexibility to change, so thank you for bringing this up. Given MDS' integration with MDAnalysis I thought it appropriate to flout the naming convention, at least for the package name. I am not wedded to this idea, however, so we can talk pros/cons on this. I have no qualms about renaming the submodules to follow convention, however.

**Comment by orbeckst** [comment]
I would keep the package name but follow PEP8 for modules. 


Am Feb 10, 2015 um 12:06 schrieb David Dotson <notifications@github.com>:

**Comment by dotsdl** [comment]
This has been fixed in 5cc386154c15a560bd00d42df7542099f3583a70. This is in the ``develop`` branch.
